# Generated by Django 6.0.1 on 2026-02-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(default='A1', max_length=5)),
                ('category', models.CharField(choices=[('daily_life', 'Daily Life'), ('work', 'Work'), ('social', 'Social'), ('travel', 'Travel'), ('culture', 'Culture')], max_length=50)),
                ('country_context', models.CharField(blank=True, help_text='CH, DE, or blank for both', max_length=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.language')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('translation_es', models.CharField(max_length=255)),
                ('pronunciation_ipa', models.CharField(blank=True, max_length=255)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adj', 'Adjective'), ('adv', 'Adverb'), ('phrase', 'Phrase'), ('prep', 'Preposition'), ('conj', 'Conjunction')], max_length=20)),
                ('gender', models.CharField(blank=True, help_text='der/die/das for German', max_length=10)),
                ('plural', models.CharField(blank=True, max_length=255)),
                ('example_sentence', models.TextField(blank=True)),
                ('example_translation', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(default='A1', max_length=5)),
                ('region_variant', models.CharField(blank=True, help_text='CH or DE for regional', max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='core.language')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_items', to='vocabulary.topic')),
            ],
            options={
                'db_table': 'vocabulary_items',
                'ordering': ['word'],
            },
        ),
    ]
