# Generated by Django 5.1 on 2026-03-17 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(choices=[('free', 'Free Conversation'), ('job_interview', 'Job Interview'), ('supermarket', 'At the Supermarket'), ('apartment', 'Apartment Hunting'), ('restaurant', 'At the Restaurant'), ('doctor', 'Doctor Visit'), ('friends', 'Meeting Friends'), ('transport', 'Public Transport')], default='free', max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('user_level', models.CharField(default='A1', max_length=5)),
                ('message_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversation_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('correction', models.TextField(blank=True, help_text='Grammar correction if user made errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversationsession')),
            ],
            options={
                'db_table': 'conversation_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
