# Generated by Django 6.0.1 on 2026-02-19 18:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SRSCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easiness_factor', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=0)),
                ('repetitions', models.IntegerField(default=0)),
                ('next_review_date', models.DateField(default=datetime.date.today)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('last_quality', models.IntegerField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to=settings.AUTH_USER_MODEL)),
                ('vocabulary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to='vocabulary.vocabularyitem')),
            ],
            options={
                'db_table': 'srs_cards',
                'unique_together': {('user', 'vocabulary_item')},
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField()),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('review_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('practice', 'Practice'), ('cram', 'Cram')], default='scheduled', max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('srs_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='srs.srscard')),
            ],
            options={
                'db_table': 'review_logs',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
