from django.core.management.base import BaseCommand
from lessons.models import Lesson, Exercise
from core.models import Language


LESSONS_DATA = [
    # -------------------------------------------------------------------------
    # ENGLISH LESSONS (for Spanish speakers moving to Switzerland)
    # -------------------------------------------------------------------------
    {
        "language_code": "en",
        "title": "Greetings & Small Talk",
        "slug": "en-greetings-small-talk",
        "description": (
            "Learn how to introduce yourself and make small talk in English. "
            "Essential for your first days in Switzerland meeting colleagues and neighbours."
        ),
        "lesson_type": "dialogue",
        "difficulty_level": "A1",
        "sort_order": 1,
        "icon": "",
        "xp_reward": 15,
        "exercises": [
            {
                "exercise_type": "multiple_choice",
                "sort_order": 1,
                "question": "Someone says 'How are you?' as a greeting. What is the most natural response?",
                "correct_answer": "Fine, thanks. And you?",
                "options": ["I am very sick today.", "Yes, I am here.", "My name is Maria."],
                "hint": "This is a polite exchange, not a medical report.",
                "explanation": "In English-speaking contexts, 'How are you?' is a greeting, not a real question. The standard reply is brief and positive, then return the question.",
                "xp_value": 2,
            },
            {
                "exercise_type": "translation",
                "sort_order": 2,
                "question": "Translate to English: 'Me llamo Ana y soy de Espana.'",
                "correct_answer": "My name is Ana and I am from Spain.",
                "options": [],
                "hint": "Use 'My name is' for 'Me llamo'.",
                "explanation": "",
                "xp_value": 2,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 3,
                "question": "Complete the sentence: 'Nice to ___ you.' (said when meeting someone for the first time)",
                "correct_answer": "meet",
                "options": [],
                "hint": "You say this when you first encounter someone.",
                "explanation": "'Nice to meet you' is the standard phrase when being introduced to someone. 'Know' is used for ongoing relationships.",
                "xp_value": 2,
            },
            {
                "exercise_type": "reorder",
                "sort_order": 4,
                "question": "Reorder the words to make a correct sentence: a / work / I / bank / at",
                "correct_answer": "I work at a bank",
                "options": ["a", "work", "I", "bank", "at"],
                "hint": "Subject + verb + place.",
                "explanation": "",
                "xp_value": 3,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 5,
                "question": "What does 'Where are you from?' mean in Spanish?",
                "correct_answer": "De donde eres?",
                "options": ["Donde vives?", "A donde vas?", "Cuanto tiempo llevas aqui?"],
                "hint": "It asks about your country of origin.",
                "explanation": "",
                "xp_value": 2,
            },
            {
                "exercise_type": "translation",
                "sort_order": 6,
                "question": "Translate to English: 'Llevo tres meses viviendo en Zurich.'",
                "correct_answer": "I have been living in Zurich for three months.",
                "options": [],
                "hint": "Use the present perfect continuous tense.",
                "explanation": "For ongoing situations that started in the past, English uses 'have been + -ing' (present perfect continuous). Spanish uses 'llevo + gerundio'.",
                "xp_value": 3,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 7,
                "question": "A: 'What do you do for a living?' B: 'I ___ a software engineer.'",
                "correct_answer": "am",
                "options": [],
                "hint": "Use the verb 'to be' for professions.",
                "explanation": "In English, professions use the verb 'to be': 'I am a teacher'. In Spanish you say 'Soy profesora' - same idea.",
                "xp_value": 2,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 8,
                "question": "Which phrase means 'Encantado/a de conocerte' in English?",
                "correct_answer": "Pleased to meet you.",
                "options": ["See you later.", "How do you do?", "Take care."],
                "hint": "It expresses pleasure at a first meeting.",
                "explanation": "",
                "xp_value": 2,
            },
        ],
    },
    {
        "language_code": "en",
        "title": "At the Supermarket",
        "slug": "en-at-the-supermarket",
        "description": (
            "Shopping vocabulary and phrases for asking for help in English. "
            "Useful at Migros, Coop, or any Swiss supermarket with English-speaking staff."
        ),
        "lesson_type": "scenario",
        "difficulty_level": "A1",
        "sort_order": 2,
        "icon": "",
        "xp_reward": 15,
        "exercises": [
            {
                "exercise_type": "multiple_choice",
                "sort_order": 1,
                "question": "You cannot find the pasta. What do you ask a staff member?",
                "correct_answer": "Excuse me, where can I find the pasta?",
                "options": [
                    "Pasta, please.",
                    "I want pasta now.",
                    "Do you have the pasta?",
                ],
                "hint": "Start with 'Excuse me' to be polite.",
                "explanation": "'Excuse me' is essential for getting someone's attention politely. Then 'where can I find...?' is natural for locating items.",
                "xp_value": 2,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 2,
                "question": "The total is 12.50 CHF. You hand over 20 CHF. The cashier gives you ___.",
                "correct_answer": "change",
                "options": [],
                "hint": "The money you get back after paying.",
                "explanation": "'Change' is the money returned after paying. In Swiss German they might say 'Rueckgeld', but in English supermarkets 'change' is universal.",
                "xp_value": 2,
            },
            {
                "exercise_type": "translation",
                "sort_order": 3,
                "question": "Translate to English: 'Donde esta la seccion de productos lacteos?'",
                "correct_answer": "Where is the dairy section?",
                "options": [],
                "hint": "'Lacteos' = dairy (milk, cheese, yogurt products).",
                "explanation": "",
                "xp_value": 2,
            },
            {
                "exercise_type": "reorder",
                "sort_order": 4,
                "question": "Reorder to form the question: bags / plastic / you / have / do",
                "correct_answer": "Do you have plastic bags",
                "options": ["bags", "plastic", "you", "have", "do"],
                "hint": "Yes/No questions start with the auxiliary verb.",
                "explanation": "Note: Many Swiss supermarkets charge for bags or don't provide them. You often need to bring your own (Migros Bag).",
                "xp_value": 3,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 5,
                "question": "What does 'expiry date' mean on a food label?",
                "correct_answer": "La fecha de caducidad",
                "options": ["El precio por kilo", "El codigo de barras", "El pais de origen"],
                "hint": "It tells you when the product is no longer safe to eat.",
                "explanation": "",
                "xp_value": 2,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 6,
                "question": "To say you want to pay by card: 'Can I pay by ___?'",
                "correct_answer": "card",
                "options": [],
                "hint": "The opposite of cash.",
                "explanation": "",
                "xp_value": 2,
            },
            {
                "exercise_type": "translation",
                "sort_order": 7,
                "question": "Translate to English: 'Tengo una alergia al gluten.'",
                "correct_answer": "I have a gluten allergy.",
                "options": [],
                "hint": "'Tengo una alergia a' = 'I have an allergy to'.",
                "explanation": "Knowing how to communicate allergies is critical. Switzerland has good gluten-free labelling on products.",
                "xp_value": 3,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 8,
                "question": "The sign says 'Buy 2, get 1 free'. What does this mean?",
                "correct_answer": "Si compras 2 unidades, la 3a es gratis.",
                "options": [
                    "Compra 1 y recibe 2 de descuento.",
                    "El segundo producto tiene un 50% de descuento.",
                    "Cada 2 semanas hay una oferta.",
                ],
                "hint": "Count carefully: you buy 2, and get a third one at no cost.",
                "explanation": "",
                "xp_value": 2,
            },
        ],
    },
    {
        "language_code": "en",
        "title": "Taking Public Transport",
        "slug": "en-taking-public-transport",
        "description": (
            "Buy tickets, read timetables, and ask for directions in English. "
            "Switzerland's public transport is world-class - this lesson helps you use it confidently."
        ),
        "lesson_type": "scenario",
        "difficulty_level": "A1",
        "sort_order": 3,
        "icon": "",
        "xp_reward": 15,
        "exercises": [
            {
                "exercise_type": "multiple_choice",
                "sort_order": 1,
                "question": "At the ticket machine, you want a single trip to the city centre. What do you select?",
                "correct_answer": "Single ticket",
                "options": ["Return ticket", "Day pass", "Monthly subscription"],
                "hint": "Single = one way, one trip.",
                "explanation": "A 'single ticket' (also called 'one-way ticket') is for one journey only. A 'return ticket' covers the journey there and back.",
                "xp_value": 2,
            },
            {
                "exercise_type": "translation",
                "sort_order": 2,
                "question": "Translate to English: 'A que hora sale el proximo tren a Berna?'",
                "correct_answer": "What time does the next train to Bern leave?",
                "options": [],
                "hint": "'Sale' = leaves/departs. 'Proximo' = next.",
                "explanation": "",
                "xp_value": 2,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 3,
                "question": "You are lost and ask: 'Excuse me, does this bus ___ to the main station?'",
                "correct_answer": "go",
                "options": [],
                "hint": "The verb for where transport travels.",
                "explanation": "'Does this bus go to...?' is the standard phrase for checking a bus or tram route.",
                "xp_value": 2,
            },
            {
                "exercise_type": "reorder",
                "sort_order": 4,
                "question": "Reorder the words: platform / train / the / leaves / which / from",
                "correct_answer": "Which platform does the train leave from",
                "options": ["platform", "train", "the", "leaves", "which", "from"],
                "hint": "Start with 'Which' - it's a question word.",
                "explanation": "",
                "xp_value": 3,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 5,
                "question": "The announcement says 'The train is delayed by 10 minutes'. What does this mean?",
                "correct_answer": "El tren llegara 10 minutos tarde.",
                "options": [
                    "El tren llega en 10 minutos.",
                    "El tren ha sido cancelado.",
                    "El tren sale en 10 minutos.",
                ],
                "hint": "'Delayed' means it will arrive or depart later than planned.",
                "explanation": "Note: Swiss trains are famously punctual, so a 10-minute delay is quite unusual!",
                "xp_value": 2,
            },
            {
                "exercise_type": "listening",
                "sort_order": 6,
                "question": "Listen and fill in the blank: 'Please ___ your ticket before boarding.'",
                "correct_answer": "validate",
                "options": [],
                "hint": "validate",
                "explanation": "In Switzerland, some routes require you to validate (stamp) your ticket before getting on. Check signs at the platform.",
                "xp_value": 3,
            },
            {
                "exercise_type": "translation",
                "sort_order": 7,
                "question": "Translate to English: 'Me he bajado en la parada equivocada.'",
                "correct_answer": "I got off at the wrong stop.",
                "options": [],
                "hint": "'Bajarse' = to get off. 'Equivocada' = wrong.",
                "explanation": "",
                "xp_value": 2,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 8,
                "question": "You need to change trains. Which word means 'transfer/change' in the context of public transport?",
                "correct_answer": "Connection",
                "options": ["Destination", "Departure", "Arrival"],
                "hint": "You need a 'connecting' train - the link between two journeys.",
                "explanation": "Timetable boards often show 'connection' time, meaning the time you have to switch from one train to another.",
                "xp_value": 2,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 9,
                "question": "The opposite of 'departure' (when a train leaves) is ___ (when it arrives).",
                "correct_answer": "arrival",
                "options": [],
                "hint": "Think of an 'arrivals' board at an airport.",
                "explanation": "",
                "xp_value": 2,
            },
        ],
    },
    {
        "language_code": "en",
        "title": "Job Interview Basics",
        "slug": "en-job-interview-basics",
        "description": (
            "Common interview questions and how to answer them professionally in English. "
            "Prepare for job interviews in Switzerland's international job market."
        ),
        "lesson_type": "dialogue",
        "difficulty_level": "A2",
        "sort_order": 4,
        "icon": "",
        "xp_reward": 20,
        "exercises": [
            {
                "exercise_type": "multiple_choice",
                "sort_order": 1,
                "question": "The interviewer asks 'Tell me about yourself.' What is the best response?",
                "correct_answer": "A brief summary of your education, experience, and why you are applying.",
                "options": [
                    "A full list of everything you have done since school.",
                    "Your personal hobbies and family situation.",
                    "A question back: 'What do you want to know?'",
                ],
                "hint": "Keep it professional and relevant to the job.",
                "explanation": "'Tell me about yourself' expects a 1-2 minute professional summary, not your life story. Focus on relevant experience and your interest in the role.",
                "xp_value": 3,
            },
            {
                "exercise_type": "translation",
                "sort_order": 2,
                "question": "Translate to English: 'Tengo cinco anios de experiencia en contabilidad.'",
                "correct_answer": "I have five years of experience in accounting.",
                "options": [],
                "hint": "'Anios de experiencia' = 'years of experience'.",
                "explanation": "",
                "xp_value": 2,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 3,
                "question": "Interviewer: 'What are your ___?' You talk about your skills and abilities.",
                "correct_answer": "strengths",
                "options": [],
                "hint": "The positive version of 'weaknesses'.",
                "explanation": "Common interview question pair: 'What are your strengths and weaknesses?' Prepare an honest, concise answer for both.",
                "xp_value": 2,
            },
            {
                "exercise_type": "reorder",
                "sort_order": 4,
                "question": "Reorder to answer why you want the job: the / company / I / admire / products / your",
                "correct_answer": "I admire your company products",
                "options": ["the", "company", "I", "admire", "products", "your"],
                "hint": "Subject + verb + object.",
                "explanation": "",
                "xp_value": 3,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 5,
                "question": "The interviewer asks 'What is your expected salary?' What does this mean?",
                "correct_answer": "Cual es tu expectativa salarial?",
                "options": [
                    "Cuanto dinero tienes ahorrado?",
                    "Cuanto has ganado antes?",
                    "Aceptas trabajar gratis al principio?",
                ],
                "hint": "'Expected' refers to what you anticipate or want.",
                "explanation": "In Switzerland, salaries are often discussed openly. Research market rates for your role before the interview.",
                "xp_value": 2,
            },
            {
                "exercise_type": "translation",
                "sort_order": 6,
                "question": "Translate to English: 'Puedo trabajar tanto de forma independiente como en equipo.'",
                "correct_answer": "I can work both independently and as part of a team.",
                "options": [],
                "hint": "'Tanto...como' = 'both...and'.",
                "explanation": "",
                "xp_value": 3,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 7,
                "question": "At the end of the interview, ask: 'When can I ___ a decision from you?'",
                "correct_answer": "expect",
                "options": [],
                "hint": "You want to know the timeline for their answer.",
                "explanation": "Asking about next steps shows professionalism and genuine interest. 'When can I expect to hear from you?' is the full phrase.",
                "xp_value": 2,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 8,
                "question": "Which phrase best expresses enthusiasm for a role?",
                "correct_answer": "I am very excited about this opportunity.",
                "options": [
                    "I suppose this job is okay.",
                    "I need this job badly.",
                    "This is not my first choice but it will do.",
                ],
                "hint": "Show genuine, professional enthusiasm.",
                "explanation": "",
                "xp_value": 2,
            },
        ],
    },
    {
        "language_code": "en",
        "title": "Renting a Flat",
        "slug": "en-renting-a-flat",
        "description": (
            "Learn vocabulary for viewing apartments and discussing lease terms in English. "
            "The Swiss rental market is competitive - knowing the right words is essential."
        ),
        "lesson_type": "scenario",
        "difficulty_level": "A2",
        "sort_order": 5,
        "icon": "",
        "xp_reward": 20,
        "exercises": [
            {
                "exercise_type": "multiple_choice",
                "sort_order": 1,
                "question": "What is a 'deposit' in the context of renting?",
                "correct_answer": "Un pago inicial que se devuelve al final del contrato si no hay danos.",
                "options": [
                    "El alquiler mensual.",
                    "Un impuesto que se paga al gobierno.",
                    "El coste de los muebles incluidos.",
                ],
                "hint": "It is kept by the landlord as security.",
                "explanation": "In Switzerland (Kaution), the deposit is typically 3 months' rent. It is held in a blocked bank account and returned at the end of the tenancy if there is no damage.",
                "xp_value": 3,
            },
            {
                "exercise_type": "translation",
                "sort_order": 2,
                "question": "Translate to English: 'Los gastos de comunidad estan incluidos en el alquiler?'",
                "correct_answer": "Are the utility bills included in the rent?",
                "options": [],
                "hint": "'Gastos de comunidad/suministros' = utility bills (water, heating, etc.).",
                "explanation": "In Switzerland, Nebenkosten (utilities/ancillary costs) may or may not be included. Always clarify this before signing.",
                "xp_value": 3,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 3,
                "question": "The period of notice required to end a rental agreement is called the ___.",
                "correct_answer": "notice period",
                "options": [],
                "hint": "You must give advance warning before leaving.",
                "explanation": "In Switzerland, the notice period for residential leases is typically 3 months, and it usually aligns with specific dates (e.g., end of March, June, September, December).",
                "xp_value": 3,
            },
            {
                "exercise_type": "reorder",
                "sort_order": 4,
                "question": "Reorder the question: the / allowed / pets / are / flat / in",
                "correct_answer": "Are pets allowed in the flat",
                "options": ["the", "allowed", "pets", "are", "flat", "in"],
                "hint": "Yes/No question: auxiliary verb goes first.",
                "explanation": "",
                "xp_value": 2,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 5,
                "question": "The landlord says the flat is 'unfurnished'. What does this mean?",
                "correct_answer": "El piso no tiene muebles.",
                "options": [
                    "El piso esta completamente amueblado.",
                    "El piso incluye electrodomesticos pero no muebles.",
                    "El piso tiene algunos muebles basicos.",
                ],
                "hint": "'Un-' is a negative prefix. 'Furnished' means with furniture.",
                "explanation": "Most Swiss flats are rented unfurnished (sin muebles), often without even a kitchen. Budget for buying appliances and furniture.",
                "xp_value": 3,
            },
            {
                "exercise_type": "translation",
                "sort_order": 6,
                "question": "Translate to English: 'Cuando podriamos mudarnos?'",
                "correct_answer": "When could we move in?",
                "options": [],
                "hint": "'Mudarse' = to move (house). 'Podriamos' = could we.",
                "explanation": "",
                "xp_value": 2,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 7,
                "question": "Before signing, you review the ___ carefully, as it is a legally binding document.",
                "correct_answer": "lease",
                "options": [],
                "hint": "The rental contract/agreement.",
                "explanation": "The 'lease' (or 'tenancy agreement') is the formal contract between landlord and tenant. In Switzerland it is often called 'Mietvertrag'.",
                "xp_value": 2,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 8,
                "question": "What does 'the landlord' mean?",
                "correct_answer": "El propietario / casero",
                "options": ["El inquilino", "El agente inmobiliario", "El vecino"],
                "hint": "This person owns the property and rents it to you.",
                "explanation": "Landlord = propietario/casero. Tenant = inquilino. Estate agent = agente inmobiliario.",
                "xp_value": 2,
            },
            {
                "exercise_type": "listening",
                "sort_order": 9,
                "question": "Listen and complete: 'The flat has a ___ balcony with views of the lake.'",
                "correct_answer": "lovely",
                "options": [],
                "hint": "lovely",
                "explanation": "",
                "xp_value": 2,
            },
        ],
    },

    # -------------------------------------------------------------------------
    # GERMAN LESSONS (for Spanish speakers moving to Switzerland)
    # -------------------------------------------------------------------------
    {
        "language_code": "de",
        "title": "Sich vorstellen",
        "slug": "de-sich-vorstellen",
        "description": (
            "Lerne, wie man sich auf Deutsch vorstellt. "
            "In der Schweiz begegnet man oft dem typisch schweizerischen 'Gruezi' statt 'Hallo'."
        ),
        "lesson_type": "dialogue",
        "difficulty_level": "A1",
        "sort_order": 1,
        "icon": "",
        "xp_reward": 15,
        "exercises": [
            {
                "exercise_type": "multiple_choice",
                "sort_order": 1,
                "question": "Como se dice 'Hola' en el dialecto suizo aleman que escucharas todos los dias?",
                "correct_answer": "Gruezi",
                "options": ["Guten Tag", "Servus", "Moin"],
                "hint": "Es una forma tipicamente suiza, no del aleman estandar.",
                "explanation": "'Gruezi' (tambien 'Gruess Gott' en algunas regiones) es el saludo formal suizo. En la calle, en tiendas, con desconocidos. 'Hallo' es mas informal y juvenil.",
                "xp_value": 3,
            },
            {
                "exercise_type": "translation",
                "sort_order": 2,
                "question": "Traduce al aleman: 'Me llamo Carlos y soy de Mexico.'",
                "correct_answer": "Ich heisse Carlos und ich komme aus Mexiko.",
                "options": [],
                "hint": "'Me llamo' = 'Ich heisse'. 'Soy de' = 'Ich komme aus'.",
                "explanation": "En aleman, 'Ich heisse' (me llamo) y 'Mein Name ist' (mi nombre es) son intercambiables para presentarse.",
                "xp_value": 2,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 3,
                "question": "Para preguntar la edad: '___ alt bist du?' (cuantos anos tienes?)",
                "correct_answer": "Wie",
                "options": [],
                "hint": "'Wie' significa 'como/cuanto' en preguntas.",
                "explanation": "'Wie alt bist du?' = Cuantos anos tienes? 'Ich bin dreissig Jahre alt.' = Tengo treinta anos.",
                "xp_value": 2,
            },
            {
                "exercise_type": "reorder",
                "sort_order": 4,
                "question": "Ordena las palabras para decir 'Trabajo como ingeniero': als / ich / Ingenieur / arbeite",
                "correct_answer": "Ich arbeite als Ingenieur",
                "options": ["als", "ich", "Ingenieur", "arbeite"],
                "hint": "En aleman, el verbo va en segunda posicion.",
                "explanation": "En aleman estandar: Sujeto + Verbo + Complemento. 'Ich arbeite als Ingenieur' = Trabajo como ingeniero.",
                "xp_value": 3,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 5,
                "question": "Que significa 'Woher kommen Sie?' (forma formal)?",
                "correct_answer": "De donde es usted?",
                "options": ["A donde va usted?", "Cuanto tiempo lleva aqui?", "Como se llama usted?"],
                "hint": "'Woher' = de donde. 'kommen' = venir.",
                "explanation": "'Sie' en mayuscula es el pronombre de cortesia (usted). En el trabajo y con desconocidos en Suiza, se usa 'Sie' hasta que alguien proponga el 'Du' (tuteo).",
                "xp_value": 3,
            },
            {
                "exercise_type": "translation",
                "sort_order": 6,
                "question": "Traduce al aleman: 'Llevo seis meses en Zurich.'",
                "correct_answer": "Ich wohne seit sechs Monaten in Zuerich.",
                "options": [],
                "hint": "Usa 'seit' (desde hace) con el presente para acciones que continuan.",
                "explanation": "Atencion: 'seit' + presente en aleman equivale a 'llevo/hace X tiempo que' en espanol. 'Ich wohne seit sechs Monaten' = Llevo seis meses viviendo aqui.",
                "xp_value": 3,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 7,
                "question": "Al despedirse formalmente en suiza se dice: '___' (en lugar de 'Tschuess').",
                "correct_answer": "Uf Wiederluege",
                "options": [],
                "hint": "Es la version dialectal suiza de 'Auf Wiedersehen'.",
                "explanation": "'Uf Wiederluege' es la despedida formal tipica en suizo aleman. 'Tschuess' existe pero suena mas aleman del norte. 'Ciao' tambien es muy comun en Suiza.",
                "xp_value": 3,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 8,
                "question": "Como se dice 'Encantado/a de conocerle' en aleman formal?",
                "correct_answer": "Freut mich, Sie kennenzulernen.",
                "options": [
                    "Ich freue mich sehr.",
                    "Schoen, dich zu sehen.",
                    "Guten Abend.",
                ],
                "hint": "'Freut mich' = me alegra/encanta.",
                "explanation": "Con 'Sie' (formal): 'Freut mich, Sie kennenzulernen.' Con 'du' (informal): 'Freut mich, dich kennenzulernen.' La diferencia es Sie/dich.",
                "xp_value": 2,
            },
        ],
    },
    {
        "language_code": "de",
        "title": "Im Supermarkt einkaufen",
        "slug": "de-im-supermarkt-einkaufen",
        "description": (
            "Einkaufsvokabular fuer Migros und Coop. "
            "Aprende a comprar en los supermercados suizos Migros y Coop con el vocabulario correcto."
        ),
        "lesson_type": "scenario",
        "difficulty_level": "A1",
        "sort_order": 2,
        "icon": "",
        "xp_reward": 15,
        "exercises": [
            {
                "exercise_type": "multiple_choice",
                "sort_order": 1,
                "question": "Estas en Migros y no encuentras el pan. Que preguntas a un empleado?",
                "correct_answer": "Entschuldigung, wo finde ich das Brot?",
                "options": [
                    "Ich moechte Brot, bitte.",
                    "Haben Sie Brot?",
                    "Das Brot ist hier.",
                ],
                "hint": "Comienza con 'Entschuldigung' (perdon/disculpe) y pregunta la ubicacion.",
                "explanation": "'Wo finde ich...?' (donde encuentro...?) es la forma mas natural de preguntar por productos en una tienda.",
                "xp_value": 2,
            },
            {
                "exercise_type": "translation",
                "sort_order": 2,
                "question": "Traduce al aleman: 'Cuanto cuesta este queso?'",
                "correct_answer": "Wie viel kostet dieser Kaese?",
                "options": [],
                "hint": "'Cuanto cuesta' = 'Wie viel kostet'. 'Este' (masculino) = 'dieser'.",
                "explanation": "Los articulos demostrativos en aleman cambian segun el genero: dieser (masc.), diese (fem.), dieses (neut.).",
                "xp_value": 3,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 3,
                "question": "En la caja: 'Moechten Sie eine ___?' (bolsa de la compra)",
                "correct_answer": "Tasche",
                "options": [],
                "hint": "La bolsa que llevas la compra a casa.",
                "explanation": "En Migros y Coop las bolsas cuestan dinero (aprox. 0.40 CHF). Es habitual llevar tu propia bolsa reutilizable.",
                "xp_value": 2,
            },
            {
                "exercise_type": "reorder",
                "sort_order": 4,
                "question": "Ordena para decir 'Pago con tarjeta': mit / ich / Karte / zahle",
                "correct_answer": "Ich zahle mit Karte",
                "options": ["mit", "ich", "Karte", "zahle"],
                "hint": "Sujeto + verbo + complemento.",
                "explanation": "'zahlen' = pagar. 'mit Karte' = con tarjeta. 'bar' = en efectivo.",
                "xp_value": 2,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 5,
                "question": "Que significa 'Haltbarkeitsdatum' en un producto?",
                "correct_answer": "La fecha de caducidad",
                "options": [
                    "El precio por kilo",
                    "El numero de lote",
                    "El pais de fabricacion",
                ],
                "hint": "'Haltbar' = duradero/conservable. 'Datum' = fecha.",
                "explanation": "'Mindesthaltbarkeitsdatum' (MHD) = fecha minima de conservacion. 'Zu verbrauchen bis' = consumir antes de. El MHD no significa que el producto este malo, solo que el fabricante garantiza la calidad hasta esa fecha.",
                "xp_value": 3,
            },
            {
                "exercise_type": "translation",
                "sort_order": 6,
                "question": "Traduce al aleman: 'Tengo alergia a los frutos secos.'",
                "correct_answer": "Ich bin allergisch gegen Nuesse.",
                "options": [],
                "hint": "'Ser alergico a' = 'allergisch sein gegen'.",
                "explanation": "Tambien puedes decir: 'Ich habe eine Nussallergie.' Las dos formas son correctas y comprensibles.",
                "xp_value": 3,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 7,
                "question": "Para pedir el recibo: 'Kann ich ___ Quittung haben, bitte?' (Kann ich... = puedo tener...?)",
                "correct_answer": "eine",
                "options": [],
                "hint": "El articulo indefinido femenino en aleman.",
                "explanation": "'Quittung' es femenino (die Quittung), por eso el articulo indefinido es 'eine'. En Migros el recibo a veces se llama 'Kassenbon'.",
                "xp_value": 3,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 8,
                "question": "Cuales son los dos principales supermercados de Suiza?",
                "correct_answer": "Migros y Coop",
                "options": [
                    "Aldi y Lidl",
                    "Carrefour y Mercadona",
                    "Spar y Rewe",
                ],
                "hint": "Son empresas suizas que dominan el mercado local.",
                "explanation": "Migros y Coop son las dos grandes cadenas suizas. Migros no vende alcohol. Tambien existen Aldi, Lidl y Denner (mas economico). Lidl y Aldi son opciones mas baratas.",
                "xp_value": 2,
            },
        ],
    },
    {
        "language_code": "de",
        "title": "Mit dem Zug fahren",
        "slug": "de-mit-dem-zug-fahren",
        "description": (
            "SBB-Tickets kaufen und nach dem Weg fragen. "
            "Aprende a usar los Ferrocarriles Federales Suizos (SBB/CFF/FFS) con confianza."
        ),
        "lesson_type": "scenario",
        "difficulty_level": "A1",
        "sort_order": 3,
        "icon": "",
        "xp_reward": 15,
        "exercises": [
            {
                "exercise_type": "multiple_choice",
                "sort_order": 1,
                "question": "Quieres comprar un billete de tren. Como se dice 'billete' en Suiza (no 'Fahrkarte')?",
                "correct_answer": "Billett",
                "options": ["Karte", "Schein", "Fahrschein"],
                "hint": "En Suiza se usa un termino de origen frances/italiano.",
                "explanation": "En Suiza, un billete de tren se llama 'Billett' (con doble t), no 'Fahrkarte' como en Alemania. Es un helvecismo tipico del suizo aleman.",
                "xp_value": 3,
            },
            {
                "exercise_type": "translation",
                "sort_order": 2,
                "question": "Traduce al aleman: 'Un billete de ida y vuelta a Lausanne, por favor.'",
                "correct_answer": "Ein Billett nach Lausanne und zurueck, bitte.",
                "options": [],
                "hint": "'Ida y vuelta' = 'und zurueck' (y de vuelta).",
                "explanation": "En las maquinas SBB puedes elegir entre 'Hinfahrt' (solo ida) y 'Hin- und Rueckfahrt' (ida y vuelta). La tarjeta del SBB-App es la opcion mas comoda.",
                "xp_value": 3,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 3,
                "question": "Para preguntar el anden: 'Von welchem ___ faehrt der Zug ab?' (de que... sale el tren?)",
                "correct_answer": "Gleis",
                "options": [],
                "hint": "La plataforma donde esperas el tren.",
                "explanation": "'Gleis' = andén/via. En los carteles del SBB verás 'Gl. 3' (Gleis 3) = Andén 3.",
                "xp_value": 2,
            },
            {
                "exercise_type": "reorder",
                "sort_order": 4,
                "question": "Ordena la pregunta: Bern / faehrt / wann / nach / der / Zug",
                "correct_answer": "Wann faehrt der Zug nach Bern",
                "options": ["Bern", "faehrt", "wann", "nach", "der", "Zug"],
                "hint": "Las preguntas con 'wann' (cuando) invierten sujeto y verbo.",
                "explanation": "En preguntas con W-Wort (wann, wo, wie...), el verbo va en segunda posicion: Wann + faehrt + der Zug + nach Bern?",
                "xp_value": 3,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 5,
                "question": "En el tren te pide el revisor el billete. Como se dice 'revisor/conductor de tren'?",
                "correct_answer": "Kondukteur",
                "options": ["Busfahrer", "Pilot", "Polizist"],
                "hint": "Es un helvecismo del frances 'conducteur'.",
                "explanation": "'Kondukteur' es la palabra suiza para el revisor de tren. En Alemania dirian 'Schaffner'. En Suiza, el termino frances ha sido adoptado al aleman.",
                "xp_value": 3,
            },
            {
                "exercise_type": "listening",
                "sort_order": 6,
                "question": "Escucha y completa: 'Der Zug hat ___ Minuten Verspaetung.' (el tren tiene... minutos de retraso)",
                "correct_answer": "fuenf",
                "options": [],
                "hint": "fuenf",
                "explanation": "En Suiza, hasta 3 minutos de retraso es considerado 'a tiempo'. La SBB tiene una puntualidad del 92% aproximadamente.",
                "xp_value": 2,
            },
            {
                "exercise_type": "translation",
                "sort_order": 7,
                "question": "Traduce al aleman: 'Tengo que transbordar en Zurich?'",
                "correct_answer": "Muss ich in Zuerich umsteigen?",
                "options": [],
                "hint": "'Transbordar/cambiar de tren' = 'umsteigen' (verbo separable).",
                "explanation": "'Umsteigen' es un verbo separable (trennbares Verb): en la pregunta va junto, pero en frases afirmativas se separa: 'Ich muss in Zuerich umsteigen.'",
                "xp_value": 3,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 8,
                "question": "El abono mensual de transporte en Suiza se llama '___' (dos palabras, significa 'suscripcion general').",
                "correct_answer": "Generalabonnement",
                "options": [],
                "hint": "Es el pase ilimitado de SBB, buses y barcos en toda Suiza.",
                "explanation": "El 'Generalabonnement' (GA) cuesta aprox. 3860 CHF/ano en 2a clase y permite viajar ilimitadamente en casi todos los transportes publicos suizos. Hay tambien el 'Halbtax' (mitad de precio en todos los viajes).",
                "xp_value": 3,
            },
        ],
    },
    {
        "language_code": "de",
        "title": "Beim Vorstellungsgespraech",
        "slug": "de-beim-vorstellungsgespraech",
        "description": (
            "Haeufige Interviewfragen auf Deutsch beantworten. "
            "Prepara tu entrevista de trabajo en aleman para el mercado laboral suizo."
        ),
        "lesson_type": "dialogue",
        "difficulty_level": "A2",
        "sort_order": 4,
        "icon": "",
        "xp_reward": 20,
        "exercises": [
            {
                "exercise_type": "multiple_choice",
                "sort_order": 1,
                "question": "El entrevistador dice 'Erzaehlen Sie mir etwas ueber sich.' Que significa?",
                "correct_answer": "Cuenteme algo sobre usted.",
                "options": [
                    "Por que quiere este trabajo?",
                    "Cuales son sus puntos debiles?",
                    "Tiene alguna pregunta para nosotros?",
                ],
                "hint": "'Erzaehlen' = contar/relatar. 'ueber sich' = sobre si mismo.",
                "explanation": "Esta es la pregunta de apertura clasica de una entrevista en aleman. Prepara un resumen profesional de 1-2 minutos: tu formacion, experiencia y por que te interesa el puesto.",
                "xp_value": 2,
            },
            {
                "exercise_type": "translation",
                "sort_order": 2,
                "question": "Traduce al aleman: 'Tengo tres anos de experiencia en marketing digital.'",
                "correct_answer": "Ich habe drei Jahre Erfahrung im digitalen Marketing.",
                "options": [],
                "hint": "'Tengo experiencia en' = 'Ich habe Erfahrung in/im'.",
                "explanation": "'Im' = 'in dem' (contraccion con el articulo dativo masculino/neutro). 'Im Marketing' = en el marketing.",
                "xp_value": 3,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 3,
                "question": "Para preguntar por el salario: 'Wie hoch ist das ___?' (cual es el salario?)",
                "correct_answer": "Gehalt",
                "options": [],
                "hint": "La compensacion economica mensual.",
                "explanation": "'Gehalt' = salario mensual para empleados. 'Lohn' = salario para trabajadores manuales. 'Bruttolohn' = salario bruto. 'Nettolohn' = salario neto.",
                "xp_value": 2,
            },
            {
                "exercise_type": "reorder",
                "sort_order": 4,
                "question": "Ordena para decir 'Trabajo bien en equipo': im / ich / arbeite / gerne / Team",
                "correct_answer": "Ich arbeite gerne im Team",
                "options": ["im", "ich", "arbeite", "gerne", "Team"],
                "hint": "'Gerne' = con gusto/me gusta. 'im Team' = en equipo.",
                "explanation": "'Gerne' es un adverbio muy util en aleman que expresa que algo se hace con placer o gusto.",
                "xp_value": 3,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 5,
                "question": "Que significa la pregunta 'Was sind Ihre Staerken?' en una entrevista?",
                "correct_answer": "Cuales son sus puntos fuertes?",
                "options": [
                    "Cuales son sus puntos debiles?",
                    "Cuanto quiere ganar?",
                    "Por que dejo su ultimo trabajo?",
                ],
                "hint": "'Staerken' viene de 'stark' (fuerte).",
                "explanation": "Preguntas tipicas en aleman: 'Staerken' (fortalezas), 'Schwaerken' (debilidades), 'Motivation' (motivacion), 'Gehaltsvorstellung' (expectativa salarial).",
                "xp_value": 2,
            },
            {
                "exercise_type": "translation",
                "sort_order": 6,
                "question": "Traduce al aleman: 'Por que quiere trabajar en nuestra empresa?'",
                "correct_answer": "Warum moechten Sie in unserem Unternehmen arbeiten?",
                "options": [],
                "hint": "'Por que' = 'Warum'. 'Querer' = 'moechten'. 'Nuestra empresa' = 'unser Unternehmen'.",
                "explanation": "",
                "xp_value": 3,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 7,
                "question": "Al final de la entrevista: 'Haben Sie noch ___?' (tiene alguna pregunta mas?)",
                "correct_answer": "Fragen",
                "options": [],
                "hint": "El plural de 'Frage' (pregunta).",
                "explanation": "Siempre prepara 2-3 preguntas para el final de la entrevista. Demuestra interes genuino. Por ejemplo: 'Wie ist die Teamstruktur?' o 'Was sind die naechsten Schritte?'",
                "xp_value": 2,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 8,
                "question": "Como te despides al final de una entrevista formal en Suiza?",
                "correct_answer": "Vielen Dank fuer das Gespraech. Auf Wiedersehen.",
                "options": [
                    "Tschuess und bis bald!",
                    "Ciao, war nett!",
                    "Okay, ich hoere von Ihnen.",
                ],
                "hint": "Agradece y usa la despedida formal.",
                "explanation": "Siempre agradece el tiempo del entrevistador. 'Vielen Dank fuer das interessante Gespraech' + apretón de manos firme es el estandar en Suiza.",
                "xp_value": 2,
            },
        ],
    },
    {
        "language_code": "de",
        "title": "Eine Wohnung mieten",
        "slug": "de-eine-wohnung-mieten",
        "description": (
            "Wohnungsbesichtigung und Mietvertrag auf Deutsch. "
            "El mercado inmobiliario suizo es muy competitivo. Aprende el vocabulario clave para encontrar piso."
        ),
        "lesson_type": "scenario",
        "difficulty_level": "A2",
        "sort_order": 5,
        "icon": "",
        "xp_reward": 20,
        "exercises": [
            {
                "exercise_type": "multiple_choice",
                "sort_order": 1,
                "question": "Que significa 'Kaution' en el contexto del alquiler en Suiza?",
                "correct_answer": "La fianza/deposito (normalmente 3 meses de alquiler).",
                "options": [
                    "El alquiler mensual total.",
                    "Los gastos de administracion.",
                    "El seguro del hogar obligatorio.",
                ],
                "hint": "Es un deposito de seguridad que se devuelve al final.",
                "explanation": "La 'Kaution' suiza (maximo 3 meses de 'Nettomiete') se deposita en una cuenta bancaria bloqueada a nombre del inquilino. Se devuelve al salir si no hay danos ni deudas.",
                "xp_value": 3,
            },
            {
                "exercise_type": "translation",
                "sort_order": 2,
                "question": "Traduce al aleman: 'Estan incluidos los gastos en el alquiler?'",
                "correct_answer": "Sind die Nebenkosten in der Miete inbegriffen?",
                "options": [],
                "hint": "'Gastos/suministros' = 'Nebenkosten'. 'Incluido' = 'inbegriffen'.",
                "explanation": "'Nebenkosten' incluye agua, calefaccion, basura, limpieza de zonas comunes. Normalmente es el 10-15% adicional sobre la 'Nettomiete' (alquiler neto).",
                "xp_value": 3,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 3,
                "question": "El contrato de alquiler se llama '___ ' en aleman. (dos palabras compuestas)",
                "correct_answer": "Mietvertrag",
                "options": [],
                "hint": "'Miete' = alquiler. 'Vertrag' = contrato.",
                "explanation": "El 'Mietvertrag' en Suiza se rige por el Codigo de Obligaciones suizo (OR). Es un documento legalmente vinculante. Leelo siempre con calma antes de firmar.",
                "xp_value": 2,
            },
            {
                "exercise_type": "reorder",
                "sort_order": 4,
                "question": "Ordena la pregunta sobre mascotas: Haustiere / erlaubt / sind / der / in / Wohnung",
                "correct_answer": "Sind Haustiere in der Wohnung erlaubt",
                "options": ["Haustiere", "erlaubt", "sind", "der", "in", "Wohnung"],
                "hint": "Pregunta de Si/No: el verbo va primero.",
                "explanation": "'Haustiere' = mascotas. 'erlaubt' = permitido. En Suiza, el propietario puede prohibir mascotas excepto animales pequenos (hamsters, peces, etc.).",
                "xp_value": 3,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 5,
                "question": "En Suiza, el piso 'EG' (Erdgeschoss) es...",
                "correct_answer": "La planta baja (planta 0).",
                "options": [
                    "El primer piso (primera planta sobre la baja).",
                    "El sotano.",
                    "El atico.",
                ],
                "hint": "'Erde' = tierra. Es el piso al nivel del suelo.",
                "explanation": "En Suiza y Alemania: EG = planta baja. 1. OG (Obergeschoss) = primer piso. DG (Dachgeschoss) = atico. UG (Untergeschoss) = sotano.",
                "xp_value": 3,
            },
            {
                "exercise_type": "translation",
                "sort_order": 6,
                "question": "Traduce al aleman: 'Cuando podriamos mudarnos?'",
                "correct_answer": "Wann koennen wir einziehen?",
                "options": [],
                "hint": "'Mudarse/entrar a vivir' = 'einziehen' (verbo separable).",
                "explanation": "'Einziehen' = mudarse a un nuevo lugar (entrar). 'Ausziehen' = mudarse de un lugar (salir). 'Umziehen' = mudarse en general.",
                "xp_value": 3,
            },
            {
                "exercise_type": "fill_blank",
                "sort_order": 7,
                "question": "Para indicar el preaviso de salida: 'Die ___ betraegt drei Monate.' (el preaviso es de tres meses)",
                "correct_answer": "Kuendigungsfrist",
                "options": [],
                "hint": "'Kuendigung' = rescision/aviso. 'Frist' = plazo.",
                "explanation": "En Suiza el plazo de preaviso ('Kuendigungsfrist') es generalmente de 3 meses. La rescision debe llegar al propietario antes del inicio del plazo. Las fechas tipicas de salida son 31/3, 30/6, 30/9 y 31/12.",
                "xp_value": 3,
            },
            {
                "exercise_type": "multiple_choice",
                "sort_order": 8,
                "question": "Que es el 'Wohnungsprotokoll' (Uebergabeprotokoll) al entrar a un piso?",
                "correct_answer": "El acta de entrega donde se documentan el estado y defectos del piso.",
                "options": [
                    "El contrato de alquiler.",
                    "La lista de normas de la comunidad de vecinos.",
                    "El recibo del deposito.",
                ],
                "hint": "Se firma entre propietario e inquilino al inicio y al final del alquiler.",
                "explanation": "El 'Uebergabeprotokoll' es fundamental en Suiza. Documenta el estado exacto del piso (paredes, suelos, electrodomesticos). Si no se firma, el propietario puede reclamarte danos preexistentes. Fotografialo todo.",
                "xp_value": 3,
            },
            {
                "exercise_type": "listening",
                "sort_order": 9,
                "question": "Escucha y completa: 'Die Wohnung hat einen grossen ___ mit Blick auf die Alpen.'",
                "correct_answer": "Balkon",
                "options": [],
                "hint": "Balkon",
                "explanation": "Un 'Balkon' (balcon) es una caracteristica muy valorada en Suiza, especialmente con vistas a los Alpes o al lago.",
                "xp_value": 2,
            },
        ],
    },
]


class Command(BaseCommand):
    help = "Seed lesson and exercise data for English and German (Spanish speakers moving to Switzerland)"

    def handle(self, *args, **options):
        self.stdout.write("Starting lesson seed...")

        try:
            lang_en = Language.objects.get(code="en")
        except Language.DoesNotExist:
            self.stderr.write("ERROR: Language with code='en' not found. Create it first.")
            return

        try:
            lang_de = Language.objects.get(code="de")
        except Language.DoesNotExist:
            self.stderr.write("ERROR: Language with code='de' not found. Create it first.")
            return

        lang_map = {"en": lang_en, "de": lang_de}

        lessons_created = 0
        lessons_updated = 0
        exercises_created = 0
        exercises_updated = 0

        for lesson_data in LESSONS_DATA:
            language = lang_map[lesson_data["language_code"]]
            exercises = lesson_data.pop("exercises")
            language_code = lesson_data.pop("language_code")

            lesson, created = Lesson.objects.update_or_create(
                slug=lesson_data["slug"],
                defaults={
                    "language": language,
                    "title": lesson_data["title"],
                    "description": lesson_data["description"],
                    "lesson_type": lesson_data["lesson_type"],
                    "difficulty_level": lesson_data["difficulty_level"],
                    "sort_order": lesson_data["sort_order"],
                    "icon": lesson_data["icon"],
                    "xp_reward": lesson_data["xp_reward"],
                    "is_active": True,
                },
            )

            if created:
                lessons_created += 1
                action = "Created"
            else:
                lessons_updated += 1
                action = "Updated"

            self.stdout.write(f"  [{action}] Lesson: {lesson.title} ({language_code.upper()}, {lesson.difficulty_level})")

            for ex_data in exercises:
                _, ex_created = Exercise.objects.update_or_create(
                    lesson=lesson,
                    sort_order=ex_data["sort_order"],
                    defaults={
                        "exercise_type": ex_data["exercise_type"],
                        "question": ex_data["question"],
                        "correct_answer": ex_data["correct_answer"],
                        "options": ex_data["options"],
                        "hint": ex_data.get("hint", ""),
                        "explanation": ex_data.get("explanation", ""),
                        "xp_value": ex_data.get("xp_value", 2),
                    },
                )
                if ex_created:
                    exercises_created += 1
                else:
                    exercises_updated += 1

            # Restore for consistent state (data was passed by ref via pop)
            lesson_data["language_code"] = language_code
            lesson_data["exercises"] = exercises

        self.stdout.write("")
        self.stdout.write(
            f"Done. Lessons: {lessons_created} created, {lessons_updated} updated. "
            f"Exercises: {exercises_created} created, {exercises_updated} updated."
        )
