# Generated by Django 6.0.1 on 2026-02-19 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('lesson_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('dialogue', 'Dialogue'), ('scenario', 'Scenario')], default='vocabulary', max_length=20)),
                ('difficulty_level', models.CharField(default='A1', max_length=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('xp_reward', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.language')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='vocabulary.topic')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['difficulty_level', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('translation', 'Translation'), ('matching', 'Matching'), ('reorder', 'Reorder Words'), ('listening', 'Listening')], max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=500)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for multiple_choice/matching')),
                ('hint', models.CharField(blank=True, max_length=500)),
                ('explanation', models.TextField(blank=True)),
                ('xp_value', models.IntegerField(default=2)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.lesson')),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_exercise', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_answered', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('xp_earned', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_lesson_progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
