CASE_EXERCISES = [
    # ==========================================
    # NOMINATIV - A1 (Subject: wer/was?)
    # ==========================================
    {
        "sentence": "___ Hund ist groß.",
        "options": ["der", "den", "dem", "des"],
        "correct": "der",
        "case": "Nominativ",
        "explanation_es": "El sujeto de la oración está en Nominativ. 'Hund' es masculino → der",
        "difficulty": "A1",
        "hint": "Subjekt → Nominativ (wer?)",
    },
    {
        "sentence": "___ Frau arbeitet hier.",
        "options": ["die", "der", "den", "dem"],
        "correct": "die",
        "case": "Nominativ",
        "explanation_es": "El sujeto está en Nominativ. 'Frau' es femenino → die",
        "difficulty": "A1",
        "hint": "Subjekt → Nominativ (wer?)",
    },
    {
        "sentence": "___ Kind spielt draußen.",
        "options": ["das", "den", "dem", "des"],
        "correct": "das",
        "case": "Nominativ",
        "explanation_es": "El sujeto está en Nominativ. 'Kind' es neutro → das",
        "difficulty": "A1",
        "hint": "Subjekt → Nominativ (wer?)",
    },
    {
        "sentence": "___ Kinder spielen im Garten.",
        "options": ["die", "der", "den", "das"],
        "correct": "die",
        "case": "Nominativ",
        "explanation_es": "El sujeto en plural está en Nominativ → die (siempre 'die' en plural Nominativ)",
        "difficulty": "A1",
        "hint": "Plural + Nominativ → die",
    },
    {
        "sentence": "___ Lehrer ist nett.",
        "options": ["der", "den", "dem", "des"],
        "correct": "der",
        "case": "Nominativ",
        "explanation_es": "'Lehrer' es el sujeto (masculino) en Nominativ → der",
        "difficulty": "A1",
        "hint": "Subjekt → Nominativ (wer?)",
    },
    {
        "sentence": "___ Auto ist neu.",
        "options": ["das", "der", "die", "den"],
        "correct": "das",
        "case": "Nominativ",
        "explanation_es": "'Auto' es neutro y es el sujeto → das",
        "difficulty": "A1",
        "hint": "Subjekt → Nominativ (was?)",
    },
    {
        "sentence": "___ Katze schläft auf dem Sofa.",
        "options": ["die", "der", "den", "dem"],
        "correct": "die",
        "case": "Nominativ",
        "explanation_es": "'Katze' es femenino y es el sujeto de la oración → die",
        "difficulty": "A1",
        "hint": "Subjekt → Nominativ (wer?)",
    },
    {
        "sentence": "Das ist ___ guter Mann.",
        "options": ["ein", "einen", "einem", "eines"],
        "correct": "ein",
        "case": "Nominativ",
        "explanation_es": "Después de 'ist' viene Nominativ. 'Mann' es masculino → ein",
        "difficulty": "A2",
        "hint": "sein + Nominativ",
    },
    {
        "sentence": "___ Studentin kommt aus Spanien.",
        "options": ["die", "der", "den", "dem"],
        "correct": "die",
        "case": "Nominativ",
        "explanation_es": "'Studentin' es femenino y es el sujeto → die",
        "difficulty": "A1",
        "hint": "Subjekt → Nominativ (wer?)",
    },
    {
        "sentence": "Das sind ___ Bücher.",
        "options": ["die", "der", "den", "das"],
        "correct": "die",
        "case": "Nominativ",
        "explanation_es": "Después de 'sind' → Nominativ. Plural → die",
        "difficulty": "A1",
        "hint": "sein + Nominativ (Plural → die)",
    },
    {
        "sentence": "___ Haus ist sehr alt.",
        "options": ["das", "der", "die", "dem"],
        "correct": "das",
        "case": "Nominativ",
        "explanation_es": "'Haus' es neutro y es el sujeto → das",
        "difficulty": "A1",
        "hint": "Subjekt → Nominativ (was?)",
    },
    {
        "sentence": "___ Bruder ist Arzt.",
        "options": ["der", "den", "dem", "des"],
        "correct": "der",
        "case": "Nominativ",
        "explanation_es": "'Bruder' es masculino y sujeto. Después de 'ist' también Nominativ (Arzt) → der",
        "difficulty": "A1",
        "hint": "Subjekt → Nominativ (wer?)",
    },
    {
        "sentence": "Es ist ___ schöne Stadt.",
        "options": ["eine", "einen", "einer", "einem"],
        "correct": "eine",
        "case": "Nominativ",
        "explanation_es": "Después de 'ist' → Nominativ. 'Stadt' es femenino → eine",
        "difficulty": "A2",
        "hint": "sein + Nominativ",
    },
    {
        "sentence": "___ Wetter ist heute schön.",
        "options": ["das", "der", "die", "dem"],
        "correct": "das",
        "case": "Nominativ",
        "explanation_es": "'Wetter' es neutro y es el sujeto → das",
        "difficulty": "A1",
        "hint": "Subjekt → Nominativ (was?)",
    },
    {
        "sentence": "Er ist ___ guter Freund.",
        "options": ["ein", "einen", "einem", "eines"],
        "correct": "ein",
        "case": "Nominativ",
        "explanation_es": "Después de 'ist' → Nominativ. 'Freund' masculino con artículo indefinido → ein",
        "difficulty": "A2",
        "hint": "sein + Nominativ",
    },

    # ==========================================
    # AKKUSATIV - A1/A2 (Direct object: wen/was?)
    # Prepositions: durch, für, gegen, ohne, um
    # ==========================================
    {
        "sentence": "Ich sehe ___ Mann.",
        "options": ["den", "der", "dem", "des"],
        "correct": "den",
        "case": "Akkusativ",
        "explanation_es": "'sehen' requiere Akkusativ (objeto directo). 'Mann' es masculino → den",
        "difficulty": "A1",
        "hint": "sehen + Akkusativ (wen?)",
    },
    {
        "sentence": "Sie kauft ___ Buch.",
        "options": ["das", "den", "dem", "des"],
        "correct": "das",
        "case": "Akkusativ",
        "explanation_es": "'kaufen' + Akkusativ. 'Buch' es neutro → das (igual que Nominativ en neutro)",
        "difficulty": "A1",
        "hint": "kaufen + Akkusativ (was?)",
    },
    {
        "sentence": "Er hat ___ Katze.",
        "options": ["eine", "einen", "einer", "einem"],
        "correct": "eine",
        "case": "Akkusativ",
        "explanation_es": "'haben' + Akkusativ. 'Katze' es femenino → eine (fem. no cambia en Akk.)",
        "difficulty": "A1",
        "hint": "haben + Akkusativ (was?)",
    },
    {
        "sentence": "Ich trinke ___ Kaffee.",
        "options": ["einen", "ein", "einem", "eines"],
        "correct": "einen",
        "case": "Akkusativ",
        "explanation_es": "'trinken' + Akkusativ. 'Kaffee' es masculino → einen (ein → einen en Akk. masc.)",
        "difficulty": "A1",
        "hint": "trinken + Akkusativ (was?)",
    },
    {
        "sentence": "Das Geschenk ist für ___ Kinder.",
        "options": ["die", "der", "den", "dem"],
        "correct": "die",
        "case": "Akkusativ",
        "explanation_es": "'für' siempre requiere Akkusativ. Plural → die",
        "difficulty": "A1",
        "hint": "für + Akkusativ",
    },
    {
        "sentence": "Wir gehen durch ___ Park.",
        "options": ["den", "der", "dem", "des"],
        "correct": "den",
        "case": "Akkusativ",
        "explanation_es": "'durch' siempre requiere Akkusativ. 'Park' es masculino → den",
        "difficulty": "A2",
        "hint": "durch + Akkusativ",
    },
    {
        "sentence": "Er kämpft gegen ___ Krankheit.",
        "options": ["die", "der", "den", "dem"],
        "correct": "die",
        "case": "Akkusativ",
        "explanation_es": "'gegen' siempre + Akkusativ. 'Krankheit' es femenino → die (no cambia en Akk.)",
        "difficulty": "A2",
        "hint": "gegen + Akkusativ",
    },
    {
        "sentence": "Sie geht ohne ___ Freund.",
        "options": ["den", "der", "dem", "des"],
        "correct": "den",
        "case": "Akkusativ",
        "explanation_es": "'ohne' siempre + Akkusativ. 'Freund' es masculino → den",
        "difficulty": "A2",
        "hint": "ohne + Akkusativ",
    },
    {
        "sentence": "Wir laufen um ___ See.",
        "options": ["den", "der", "dem", "des"],
        "correct": "den",
        "case": "Akkusativ",
        "explanation_es": "'um' siempre + Akkusativ. 'See' (el lago) es masculino → den",
        "difficulty": "A2",
        "hint": "um + Akkusativ",
    },
    {
        "sentence": "Ich lese ___ Zeitung.",
        "options": ["die", "der", "den", "dem"],
        "correct": "die",
        "case": "Akkusativ",
        "explanation_es": "'lesen' + Akkusativ. 'Zeitung' es femenino → die (fem. no cambia en Akk.)",
        "difficulty": "A1",
        "hint": "lesen + Akkusativ (was?)",
    },
    {
        "sentence": "Hast du ___ Bruder?",
        "options": ["einen", "ein", "einem", "einer"],
        "correct": "einen",
        "case": "Akkusativ",
        "explanation_es": "'haben' + Akkusativ. 'Bruder' es masculino → einen",
        "difficulty": "A1",
        "hint": "haben + Akkusativ (wen?)",
    },
    {
        "sentence": "Ich brauche ___ Computer.",
        "options": ["einen", "ein", "einem", "einer"],
        "correct": "einen",
        "case": "Akkusativ",
        "explanation_es": "'brauchen' + Akkusativ. 'Computer' es masculino → einen",
        "difficulty": "A1",
        "hint": "brauchen + Akkusativ (was?)",
    },
    {
        "sentence": "Kennst du ___ Frau dort?",
        "options": ["die", "der", "den", "dem"],
        "correct": "die",
        "case": "Akkusativ",
        "explanation_es": "'kennen' + Akkusativ. 'Frau' es femenino → die (no cambia)",
        "difficulty": "A1",
        "hint": "kennen + Akkusativ (wen?)",
    },
    {
        "sentence": "Das ist nichts für ___ schwachen Mann.",
        "options": ["einen", "ein", "einem", "einer"],
        "correct": "einen",
        "case": "Akkusativ",
        "explanation_es": "'für' + Akkusativ. 'Mann' es masculino → einen",
        "difficulty": "A2",
        "hint": "für + Akkusativ",
    },
    {
        "sentence": "Er sucht ___ Schlüssel.",
        "options": ["den", "der", "dem", "des"],
        "correct": "den",
        "case": "Akkusativ",
        "explanation_es": "'suchen' + Akkusativ. 'Schlüssel' es masculino → den",
        "difficulty": "A1",
        "hint": "suchen + Akkusativ (was?)",
    },

    # ==========================================
    # DATIV - A2 (Indirect object: wem?)
    # Prepositions: aus, bei, mit, nach, seit, von, zu
    # Verbs: helfen, danken, gehören, gefallen, etc.
    # ==========================================
    {
        "sentence": "Ich helfe ___ Frau.",
        "options": ["der", "die", "den", "des"],
        "correct": "der",
        "case": "Dativ",
        "explanation_es": "'helfen' siempre + Dativ. 'Frau' es femenino → der (die → der en Dativ!)",
        "difficulty": "A2",
        "hint": "helfen + Dativ (wem?)",
    },
    {
        "sentence": "Er kommt aus ___ Schweiz.",
        "options": ["der", "die", "den", "dem"],
        "correct": "der",
        "case": "Dativ",
        "explanation_es": "'aus' siempre + Dativ. 'Schweiz' es femenino → der",
        "difficulty": "A2",
        "hint": "aus + Dativ",
    },
    {
        "sentence": "Wir fahren mit ___ Zug.",
        "options": ["dem", "den", "der", "des"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'mit' siempre + Dativ. 'Zug' es masculino → dem (der → dem en Dativ!)",
        "difficulty": "A2",
        "hint": "mit + Dativ",
    },
    {
        "sentence": "Sie wohnt bei ___ Familie.",
        "options": ["der", "die", "den", "dem"],
        "correct": "der",
        "case": "Dativ",
        "explanation_es": "'bei' siempre + Dativ. 'Familie' es femenino → der",
        "difficulty": "A2",
        "hint": "bei + Dativ",
    },
    {
        "sentence": "Ich gehe zu ___ Arzt.",
        "options": ["dem", "den", "der", "des"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'zu' siempre + Dativ. 'Arzt' es masculino → dem",
        "difficulty": "A2",
        "hint": "zu + Dativ",
    },
    {
        "sentence": "Er spricht mit ___ Lehrerin.",
        "options": ["der", "die", "den", "dem"],
        "correct": "der",
        "case": "Dativ",
        "explanation_es": "'mit' + Dativ. 'Lehrerin' es femenino → der",
        "difficulty": "A2",
        "hint": "mit + Dativ",
    },
    {
        "sentence": "Das Buch gehört ___ Kind.",
        "options": ["dem", "den", "der", "das"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'gehören' + Dativ. 'Kind' es neutro → dem (das → dem en Dativ!)",
        "difficulty": "A2",
        "hint": "gehören + Dativ (wem?)",
    },
    {
        "sentence": "Nach ___ Arbeit gehe ich nach Hause.",
        "options": ["der", "die", "den", "dem"],
        "correct": "der",
        "case": "Dativ",
        "explanation_es": "'nach' + Dativ. 'Arbeit' es femenino → der",
        "difficulty": "A2",
        "hint": "nach + Dativ",
    },
    {
        "sentence": "Seit ___ Jahr lerne ich Deutsch.",
        "options": ["einem", "ein", "einen", "eines"],
        "correct": "einem",
        "case": "Dativ",
        "explanation_es": "'seit' + Dativ. 'Jahr' es neutro → einem (ein → einem en Dativ!)",
        "difficulty": "A2",
        "hint": "seit + Dativ",
    },
    {
        "sentence": "Er dankt ___ Mutter.",
        "options": ["der", "die", "den", "dem"],
        "correct": "der",
        "case": "Dativ",
        "explanation_es": "'danken' + Dativ. 'Mutter' es femenino → der",
        "difficulty": "A2",
        "hint": "danken + Dativ (wem?)",
    },
    {
        "sentence": "Das Kleid gefällt ___ Mädchen.",
        "options": ["dem", "den", "der", "das"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'gefallen' + Dativ. 'Mädchen' es neutro → dem",
        "difficulty": "A2",
        "hint": "gefallen + Dativ (wem?)",
    },
    {
        "sentence": "Ich schreibe ___ Freund einen Brief.",
        "options": ["dem", "den", "der", "des"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'schreiben' + Dativ (a quién) + Akk (qué). 'Freund' masc. en Dativ → dem",
        "difficulty": "A2",
        "hint": "schreiben + Dativ (wem?) + Akkusativ (was?)",
    },
    {
        "sentence": "Von ___ Bahnhof sind es 10 Minuten.",
        "options": ["dem", "den", "der", "des"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'von' siempre + Dativ. 'Bahnhof' es masculino → dem",
        "difficulty": "A2",
        "hint": "von + Dativ",
    },
    {
        "sentence": "Sie gibt ___ Kindern Schokolade.",
        "options": ["den", "die", "der", "dem"],
        "correct": "den",
        "case": "Dativ",
        "explanation_es": "'geben' + Dativ. Plural en Dativ → den (+ sustantivo recibe -n: Kindern)",
        "difficulty": "A2",
        "hint": "geben + Dativ (wem?) - Plural Dativ → den",
    },
    {
        "sentence": "Ich fahre mit ___ Bus zur Schule.",
        "options": ["dem", "den", "der", "des"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'mit' + Dativ. 'Bus' es masculino → dem",
        "difficulty": "A2",
        "hint": "mit + Dativ",
    },

    # ==========================================
    # GENITIV - B1 (Possession: wessen?)
    # Prepositions: während, wegen, trotz, statt
    # ==========================================
    {
        "sentence": "Das Auto ___ Mannes ist rot.",
        "options": ["des", "dem", "den", "der"],
        "correct": "des",
        "case": "Genitiv",
        "explanation_es": "Genitiv de posesión (¿de quién?). 'Mann' es masculino → des (+es: Mannes)",
        "difficulty": "B1",
        "hint": "Genitiv (wessen?) - Maskulin/Neutrum → des",
    },
    {
        "sentence": "Trotz ___ Wetters gehen wir raus.",
        "options": ["des", "dem", "den", "der"],
        "correct": "des",
        "case": "Genitiv",
        "explanation_es": "'trotz' + Genitiv. 'Wetter' es neutro → des (+s: Wetters)",
        "difficulty": "B1",
        "hint": "trotz + Genitiv",
    },
    {
        "sentence": "Die Tasche ___ Frau ist schön.",
        "options": ["der", "die", "den", "des"],
        "correct": "der",
        "case": "Genitiv",
        "explanation_es": "Genitiv de posesión. 'Frau' es femenino → der (die → der en Genitiv!)",
        "difficulty": "B1",
        "hint": "Genitiv (wessen?) - Feminin → der",
    },
    {
        "sentence": "Während ___ Sommers reise ich viel.",
        "options": ["des", "dem", "den", "der"],
        "correct": "des",
        "case": "Genitiv",
        "explanation_es": "'während' + Genitiv. 'Sommer' es masculino → des (+s: Sommers)",
        "difficulty": "B1",
        "hint": "während + Genitiv",
    },
    {
        "sentence": "Wegen ___ Regens bleiben wir zu Hause.",
        "options": ["des", "dem", "den", "der"],
        "correct": "des",
        "case": "Genitiv",
        "explanation_es": "'wegen' + Genitiv. 'Regen' es masculino → des (+s: Regens)",
        "difficulty": "B1",
        "hint": "wegen + Genitiv",
    },
    {
        "sentence": "Das Spielzeug ___ Kindes liegt hier.",
        "options": ["des", "dem", "den", "der"],
        "correct": "des",
        "case": "Genitiv",
        "explanation_es": "Genitiv de posesión. 'Kind' es neutro → des (+es: Kindes)",
        "difficulty": "B1",
        "hint": "Genitiv (wessen?) - Neutrum → des",
    },
    {
        "sentence": "Statt ___ Autos nehme ich den Bus.",
        "options": ["des", "dem", "den", "der"],
        "correct": "des",
        "case": "Genitiv",
        "explanation_es": "'statt' + Genitiv. 'Auto' es neutro → des (+s: Autos)",
        "difficulty": "B1",
        "hint": "statt + Genitiv",
    },
    {
        "sentence": "Die Meinung ___ Leute ist unterschiedlich.",
        "options": ["der", "die", "den", "des"],
        "correct": "der",
        "case": "Genitiv",
        "explanation_es": "Genitiv de posesión. Plural → der (siempre 'der' en Genitiv plural)",
        "difficulty": "B1",
        "hint": "Genitiv (wessen?) - Plural → der",
    },
    {
        "sentence": "Die Farbe ___ Hauses gefällt mir.",
        "options": ["des", "dem", "den", "der"],
        "correct": "des",
        "case": "Genitiv",
        "explanation_es": "Genitiv de posesión. 'Haus' es neutro → des (+es: Hauses)",
        "difficulty": "B1",
        "hint": "Genitiv (wessen?) - Neutrum → des",
    },
    {
        "sentence": "Wegen ___ Krankheit kann sie nicht kommen.",
        "options": ["der", "die", "den", "des"],
        "correct": "der",
        "case": "Genitiv",
        "explanation_es": "'wegen' + Genitiv. 'Krankheit' es femenino → der",
        "difficulty": "B1",
        "hint": "wegen + Genitiv - Feminin → der",
    },

    # ==========================================
    # WECHSELPRÄPOSITIONEN - B1
    # in, an, auf, über, unter, vor, hinter, neben, zwischen
    # Akkusativ = movimiento (wohin?)
    # Dativ = posición (wo?)
    # ==========================================
    {
        "sentence": "Ich gehe in ___ Schule.",
        "options": ["die", "der", "den", "dem"],
        "correct": "die",
        "case": "Akkusativ",
        "explanation_es": "'in' + Akkusativ = movimiento (¿a dónde voy?). 'Schule' es femenino → die",
        "difficulty": "B1",
        "hint": "Wechselpräposition: in + Akk. (wohin?) = movimiento",
    },
    {
        "sentence": "Ich bin in ___ Schule.",
        "options": ["der", "die", "den", "dem"],
        "correct": "der",
        "case": "Dativ",
        "explanation_es": "'in' + Dativ = posición (¿dónde estoy?). 'Schule' es femenino → der",
        "difficulty": "B1",
        "hint": "Wechselpräposition: in + Dat. (wo?) = posición",
    },
    {
        "sentence": "Er legt das Buch auf ___ Tisch.",
        "options": ["den", "der", "dem", "des"],
        "correct": "den",
        "case": "Akkusativ",
        "explanation_es": "'auf' + Akkusativ = movimiento (pone el libro sobre la mesa). 'Tisch' masc. → den",
        "difficulty": "B1",
        "hint": "Wechselpräposition: auf + Akk. (wohin?) = movimiento",
    },
    {
        "sentence": "Das Buch liegt auf ___ Tisch.",
        "options": ["dem", "den", "der", "des"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'auf' + Dativ = posición (el libro está sobre la mesa). 'Tisch' masc. → dem",
        "difficulty": "B1",
        "hint": "Wechselpräposition: auf + Dat. (wo?) = posición",
    },
    {
        "sentence": "Sie hängt das Bild an ___ Wand.",
        "options": ["die", "der", "den", "dem"],
        "correct": "die",
        "case": "Akkusativ",
        "explanation_es": "'an' + Akkusativ = movimiento (cuelga en la pared). 'Wand' femenino → die",
        "difficulty": "B1",
        "hint": "Wechselpräposition: an + Akk. (wohin?)",
    },
    {
        "sentence": "Das Bild hängt an ___ Wand.",
        "options": ["der", "die", "den", "dem"],
        "correct": "der",
        "case": "Dativ",
        "explanation_es": "'an' + Dativ = posición (el cuadro está en la pared). 'Wand' femenino → der",
        "difficulty": "B1",
        "hint": "Wechselpräposition: an + Dat. (wo?)",
    },
    {
        "sentence": "Die Katze springt unter ___ Bett.",
        "options": ["das", "dem", "den", "der"],
        "correct": "das",
        "case": "Akkusativ",
        "explanation_es": "'unter' + Akkusativ = movimiento (salta debajo de la cama). 'Bett' neutro → das",
        "difficulty": "B1",
        "hint": "Wechselpräposition: unter + Akk. (wohin?)",
    },
    {
        "sentence": "Die Katze schläft unter ___ Bett.",
        "options": ["dem", "das", "den", "der"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'unter' + Dativ = posición (duerme debajo de la cama). 'Bett' neutro → dem",
        "difficulty": "B1",
        "hint": "Wechselpräposition: unter + Dat. (wo?)",
    },
    {
        "sentence": "Stell die Lampe neben ___ Sofa.",
        "options": ["das", "dem", "den", "der"],
        "correct": "das",
        "case": "Akkusativ",
        "explanation_es": "'neben' + Akkusativ = movimiento (pon la lámpara al lado del sofá). 'Sofa' neutro → das",
        "difficulty": "B1",
        "hint": "Wechselpräposition: neben + Akk. (wohin?)",
    },
    {
        "sentence": "Die Lampe steht neben ___ Sofa.",
        "options": ["dem", "das", "den", "der"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'neben' + Dativ = posición (la lámpara está al lado del sofá). 'Sofa' neutro → dem",
        "difficulty": "B1",
        "hint": "Wechselpräposition: neben + Dat. (wo?)",
    },
    {
        "sentence": "Er stellt sich vor ___ Spiegel.",
        "options": ["den", "dem", "der", "des"],
        "correct": "den",
        "case": "Akkusativ",
        "explanation_es": "'vor' + Akkusativ = movimiento (se pone delante del espejo). 'Spiegel' masc. → den",
        "difficulty": "B1",
        "hint": "Wechselpräposition: vor + Akk. (wohin?)",
    },
    {
        "sentence": "Er steht vor ___ Spiegel.",
        "options": ["dem", "den", "der", "des"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'vor' + Dativ = posición (está delante del espejo). 'Spiegel' masc. → dem",
        "difficulty": "B1",
        "hint": "Wechselpräposition: vor + Dat. (wo?)",
    },

    # ==========================================
    # MIXED / TRICKY - B1
    # ==========================================
    {
        "sentence": "Ich gebe ___ Lehrer das Buch.",
        "options": ["dem", "den", "der", "des"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'geben' + Dativ (a quién) + Akk (qué). 'Lehrer' es el destinatario (Dativ) → dem",
        "difficulty": "A2",
        "hint": "geben + Dativ (wem?) + Akkusativ (was?)",
    },
    {
        "sentence": "Ich kaufe ___ Schwester ein Geschenk.",
        "options": ["der", "die", "den", "dem"],
        "correct": "der",
        "case": "Dativ",
        "explanation_es": "'kaufen' + Dativ (para quién) + Akk (qué). 'Schwester' fem. en Dativ → der",
        "difficulty": "A2",
        "hint": "kaufen + Dativ (wem?) + Akkusativ (was?)",
    },
    {
        "sentence": "Er zeigt ___ Freundin die Stadt.",
        "options": ["der", "die", "den", "dem"],
        "correct": "der",
        "case": "Dativ",
        "explanation_es": "'zeigen' + Dativ (a quién) + Akk (qué). 'Freundin' fem. en Dativ → der",
        "difficulty": "A2",
        "hint": "zeigen + Dativ (wem?) + Akkusativ (was?)",
    },
    {
        "sentence": "Das Essen schmeckt ___ Gästen gut.",
        "options": ["den", "die", "der", "dem"],
        "correct": "den",
        "case": "Dativ",
        "explanation_es": "'schmecken' + Dativ. Plural en Dativ → den (+ -n: Gästen)",
        "difficulty": "B1",
        "hint": "schmecken + Dativ (wem?) - Plural Dativ → den",
    },
    {
        "sentence": "Innerhalb ___ Stadt gibt es viele Parks.",
        "options": ["der", "die", "den", "des"],
        "correct": "der",
        "case": "Genitiv",
        "explanation_es": "'innerhalb' + Genitiv. 'Stadt' es femenino → der",
        "difficulty": "B1",
        "hint": "innerhalb + Genitiv",
    },
    {
        "sentence": "Er erzählt ___ Kindern eine Geschichte.",
        "options": ["den", "die", "der", "dem"],
        "correct": "den",
        "case": "Dativ",
        "explanation_es": "'erzählen' + Dativ (a quién) + Akk (qué). Plural Dativ → den",
        "difficulty": "A2",
        "hint": "erzählen + Dativ (wem?) - Plural Dativ → den",
    },
    {
        "sentence": "Außerhalb ___ Landes ist es anders.",
        "options": ["des", "dem", "den", "der"],
        "correct": "des",
        "case": "Genitiv",
        "explanation_es": "'außerhalb' + Genitiv. 'Land' es neutro → des (+es: Landes)",
        "difficulty": "B1",
        "hint": "außerhalb + Genitiv",
    },
    {
        "sentence": "Sie fährt in ___ Stadt.",
        "options": ["die", "der", "den", "dem"],
        "correct": "die",
        "case": "Akkusativ",
        "explanation_es": "'in' + Akk. = movimiento (va a la ciudad). 'Stadt' femenino → die",
        "difficulty": "B1",
        "hint": "Wechselpräposition: in + Akk. (wohin?)",
    },
    {
        "sentence": "Sie lebt in ___ Stadt.",
        "options": ["der", "die", "den", "dem"],
        "correct": "der",
        "case": "Dativ",
        "explanation_es": "'in' + Dativ = posición (vive en la ciudad). 'Stadt' femenino → der",
        "difficulty": "B1",
        "hint": "Wechselpräposition: in + Dat. (wo?)",
    },
    {
        "sentence": "Trotz ___ Problems hat er es geschafft.",
        "options": ["des", "dem", "den", "der"],
        "correct": "des",
        "case": "Genitiv",
        "explanation_es": "'trotz' + Genitiv. 'Problem' es neutro → des (+s: Problems)",
        "difficulty": "B1",
        "hint": "trotz + Genitiv",
    },
    {
        "sentence": "Die Mutter gibt ___ Sohn Geld.",
        "options": ["dem", "den", "der", "des"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'geben' + Dativ (a quién). 'Sohn' es masculino → dem",
        "difficulty": "A2",
        "hint": "geben + Dativ (wem?)",
    },
    {
        "sentence": "Während ___ Pause trinke ich Kaffee.",
        "options": ["der", "die", "den", "des"],
        "correct": "der",
        "case": "Genitiv",
        "explanation_es": "'während' + Genitiv. 'Pause' es femenino → der",
        "difficulty": "B1",
        "hint": "während + Genitiv - Feminin → der",
    },
    {
        "sentence": "Das Handy liegt zwischen ___ Büchern.",
        "options": ["den", "die", "der", "dem"],
        "correct": "den",
        "case": "Dativ",
        "explanation_es": "'zwischen' + Dativ = posición (está entre los libros). Plural Dativ → den",
        "difficulty": "B1",
        "hint": "Wechselpräposition: zwischen + Dat. (wo?)",
    },
    {
        "sentence": "Leg das Handy zwischen ___ Bücher.",
        "options": ["die", "den", "der", "dem"],
        "correct": "die",
        "case": "Akkusativ",
        "explanation_es": "'zwischen' + Akk. = movimiento (pon el móvil entre los libros). Plural Akk. → die",
        "difficulty": "B1",
        "hint": "Wechselpräposition: zwischen + Akk. (wohin?)",
    },
    {
        "sentence": "Er versteckt sich hinter ___ Baum.",
        "options": ["dem", "den", "der", "des"],
        "correct": "dem",
        "case": "Dativ",
        "explanation_es": "'hinter' + Dativ = posición (se esconde detrás del árbol). 'Baum' masc. → dem",
        "difficulty": "B1",
        "hint": "Wechselpräposition: hinter + Dat. (wo?)",
    },
    {
        "sentence": "Er geht hinter ___ Baum.",
        "options": ["den", "dem", "der", "des"],
        "correct": "den",
        "case": "Akkusativ",
        "explanation_es": "'hinter' + Akk. = movimiento (va detrás del árbol). 'Baum' masc. → den",
        "difficulty": "B1",
        "hint": "Wechselpräposition: hinter + Akk. (wohin?)",
    },
]

CASE_COLORS = {
    "Nominativ": {"bg": "bg-blue-100 dark:bg-blue-900/30", "text": "text-blue-700 dark:text-blue-300", "border": "border-blue-400"},
    "Akkusativ": {"bg": "bg-green-100 dark:bg-green-900/30", "text": "text-green-700 dark:text-green-300", "border": "border-green-400"},
    "Dativ": {"bg": "bg-purple-100 dark:bg-purple-900/30", "text": "text-purple-700 dark:text-purple-300", "border": "border-purple-400"},
    "Genitiv": {"bg": "bg-orange-100 dark:bg-orange-900/30", "text": "text-orange-700 dark:text-orange-300", "border": "border-orange-400"},
}
